### ISSUE TITLE
ModuleNotFoundError: No module named 'data.multisource_dataset'

### ISSUE THREAD

**Issue by OldSixOne** [iamyufan/MF-Net#1]
我没有找到这个呀 ModuleNotFoundError: No module named 'data.multisource_dataset'

**Comment by iamyufan** [comment]
Fixed by changing the `multisource` into `font` in the latest commit (https://github.com/iamyufan/MF-Net/commit/8ce3ee73616d54bb469f6155307c9604874e13fe).

Feel free to open a new issue if you have encountered anything else unexpected :)
